module.exports = {
  _HOME: {
    _INTRO: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur consequuntur est ex excepturi itaque labore maxime pariatur qui sint voluptatibus.",
    _LEARN_MORE: "Learn more",
    _BACK_TO_THE_TOP: "Back to the top"
  },
  _FORMS: {
    _REGISTER_TITLE: "Registration",
    _LOGIN_TITLE: "Login",
    _SOCIALS_SUBTITLE: "You can log in with your favorite social networks :",
    _REGISTER_SUBTITLE: "Welcome ! Please fill in some information to register :",
    _EMAIL_ADDRESS: "Email address",
    _USERNAME: "Username",
    _FIRSTNAME_LASTNAME: "First name and last name",
    _PASSWORD: "Password",
    _PASSWORD_PLACEHOLDER: "Choose a strong password",
    _CONFIRMATION: "Password confirmation",
    _CONFIRMATION_PLACEHOLDER: "Rewrite the chosen password",
    _REGISTER_BUTTON: "Create account",
    _LOGIN_SUBTITLE: "You can log in with your credentials :",
    _EMAIL_OR_USERNAME: "Email or username",
    _EMAIL_OR_USERNAME_PLACEHOLDER: "Your email address or username",
    _FORGOTTEN: "forgotten",
    _LOGIN_PASSWORD_PLACEHOLDER: "Your password",
    _LOGIN_BUTTON: "Login",
    _FORGOT_PWD_SUBTITLE: "We can send you a password reset link to the email address linked to your account :",
    _FORGOT_PWD_EMAIL_PLACEHOLDER: "The email address linked to your account",
    _FORGOT_PWD_BUTTON: "Send",
    _CHANGE_PWD_SUBTITLE: "You can change your password :",
    _NEW_PASSWORD: "New password",
    _CHANGE_PWD_BUTTON: "Modify",
    _VALIDATE_SUCCESS: "Your account is verified. You can now login.",
    _VALIDATE_ERROR: "Invalid link. Check the email we sent you.",
    _FORGOT_SUCCESS: "Your password has been changed. You can now login."
  },
  _PASSWORD_VALIDATOR: {
    _8_CHARS: "At least 8 characters.",
    _LOWERCASE: "At least 1 lowercase letter.",
    _UPPERCASE: "At least 1 uppercase letter.",
    _NUMBER: "At least 1 number."
  },
  _HEADER: {
    _HOME: "Home page",
    _ALL_MOVIES: "All movies",
    _MY_ACCOUNT: "My account",
    _THEME: "Theme",
    _DARK_MODE: "Dark mode",
    _NEON_EFFECT: "Neon effect",
    _SECONDARY_COLOR: "Custom color"
  },
  _MOVIES: {
    _SORT_TITLE: "Sorting by :",
    _FILTER_TITLE: "Filter movies by...",
    _S_SORT_BY: "Sort by...",
    _S_ALPHA: "Alphabetical order",
    _S_RELEVANCE: "Relevance",
    _S_FIRST: "Show firstly...",
    _S_BEST_RATED: "The best rated",
    _S_LOWEST_RATED: "The worst movies",
    _S_MOST_RECENT: "The most recent ones",
    _S_OLDEST: "The oldest ones",
    _GENRE_TITLE: "Genre",
    _G_ACTION: "Action",
    _G_ADVENTURE: "Adventure",
    _G_ANIMATION: "Animation",
    _G_BIOGRAPHY: "Biography",
    _G_COMEDY: "Comedy",
    _G_CRIME: "Crime",
    _G_DOCUMENTARY: "Documentary",
    _G_DRAMA: "Drama",
    _G_FAMILY: "Family",
    _G_FANTASY: "Fantasy",
    _G_FILM_NOIR: "Film Noir",
    _G_HISTORY: "History",
    _G_HORROR: "Horror",
    _G_MUSIC: "Music",
    _G_MUSICAL: "Musical",
    _G_MYSTERY: "Mystery",
    _G_ROMANCE: "Romance",
    _G_SCI_FI: "Sci-Fi",
    _G_SHORT_FILM: "Short Film",
    _G_SPORT: "Sport",
    _G_SUPERHERO: "Superhero",
    _G_THRILLER: "Thriller",
    _G_WAR: "War",
    _G_WESTERN: "Western",
    _FILTER_YEAR_TITLE: "Filter by release date :",
    _FILTER_RATING_TITLE: "Filter by ratings :",
    _SEARCH_SUBMIT: "Search for movies",
    _NOT_SEEN: "Go to the movie page",
    _SEEN: "You already watched this movie"
  },
  _MOVIE_PAGE: {
    _SIDE_LABEL: "Streaming :",
    _MAIN_LABEL: "Informations :",
    _ACTORS: "Actors :",
    _GENRES: "Genres :",
    _SYNOPSIS: "Synopsis :",
    _RELEASE_DATE: "Release date :",
    _RATINGS: "Ratings :",
    _PRODUCTION: "Production :",
    _AWARDS: "Awards :",
    _COMMENTS_LABEL: "Comments :",
    _WRITE_COMMENT: "Write a comment...",
    _COMMENTS_BUTTON: "Send the comment",
    _COMMENTS_PLACEHOLDER: "Give your opinion about this movie.",
    _COMMENTS_NONE: "There are no comments for this movie yet."
  },
  _PROFILE: {
    _TAB_INFOS: "Infos",
    _TAB_MOVIES: "Movies",
    _USERNAME: "Username",
    _FIRSTNAME: "First name",
    _LASTNAME: "Last name",
  },
  _ERROR: {
    _ERROR_TEXT: "Oops! Something went wrong."
  },
  _ACCOUNT: {
    _A_INFOS_TITLE: "My infos :",
    _A_MOVIES_TITLE: "My watched movies :",
    _UPDATE_INFOS: "Update my infos"
  },
  _FOOTER: {
    _WELCOME: "Welcome",
    _BY: "By"
  }
};