// TRANSLATION
export const GET_TRANSLATION = 'GET_TRANSLATION';
export const TRANSLATION_LOADING = 'TRANSLATION_LOADING';
export const SET_LANGUAGE = 'SET_LANGUAGE';
// AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';